networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

services:
  web:
    env_file: ".env"
    platform: linux/x86_64
    ports:
      - "127.0.0.1:8090:8080"
      - "127.0.0.1:8091:8081"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
