networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

services:
  web:
    env_file: ".env"
    platform: linux/x86_64
    ports:
      - "127.0.0.1:80:8080"
      - "127.0.0.1:81:8081"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
  local:
    env_file: ".env"
    platform: linux/x86_64
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
