
networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"

services:
  web:
    env_file: ".env"
    platform: linux/x86_64
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
  local:
    env_file: ".env"
    platform: linux/x86_64
    ports:
      - "8080:8080"
      - "8081:8081"

    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=quass.email
      - SUBDOMAINS=api,
      - VALIDATION=http
      - EMAIL=webmaster@quass.email #optional
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=false #optional
    volumes:
      - /config/api.subdomain.conf:/config/nginx/site-confs/default.conf

    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    networks:
      - backend
