networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"

services:
  web:
    env_file: ".env"
    platform: linux/x86_64
    ports:
      - "80:8080"
      - "81:8081"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
  local:
    env_file: ".env"
    platform: linux/x86_64
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
